### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by ylmyg** [mehayou/PhotoSelector#2]
我们现在有一个需求是这样的，硬件发送一个指令打开手机的相机，然后在接收一个指令拍照，我怎么能监听到系统相机的拍照事件呢？

**Comment by mehayou** [comment]
问题不属于本项目，看到已经是过来大半年，希望已经找到解决方法，感谢您的提问。
另：如果系统没有提供相关监听事件，或许可以考虑ContentObserver监听媒体库变化来判断。
