### ISSUE TITLE
针对 `Gradle` 找不到 `PhotoSelector` 的解决方案

### ISSUE THREAD

**Issue by ADE150** [mehayou/PhotoSelector#3]
**问题：**

按照步骤来，在写代码时会找不到 `PhotoSelector`，如图：

![image](https://user-images.githubusercontent.com/84427028/179035216-03a26633-be83-45d3-a140-a4d2fdac3520.png)

**原因：**

`Gradle` 识别依赖新版本的方式过时

解决方法：使用 `latest.release` 添加依赖

```groovy
implementation 'com.mehayou:photoselector:latest.release'
```

或者添加当前版本：

```groovy
implementation 'com.mehayou:photoselector:1.0.3'
```

**Comment by mehayou** [comment]
此前已有标注`参照最终版本名称替换下面的“releases”`
可能标注不明显，已做修改，感谢您的关注和提问。
